using UnityEngine;
using System.Collections;

namespace M8 {
    //custom key mapping
    public enum InputKeyMap : int {
        None = -1,

#if OUYA
        BUTTON_O = OuyaSDK.BUTTON_O,
        BUTTON_U = OuyaSDK.BUTTON_U,
        BUTTON_Y = OuyaSDK.KEYCODE_BUTTON_Y,
        BUTTON_A = OuyaSDK.BUTTON_A,
        BUTTON_LB = OuyaSDK.BUTTON_LB,
        BUTTON_LT = OuyaSDK.KEYCODE_BUTTON_L2,
        BUTTON_RB = OuyaSDK.BUTTON_RB,
        BUTTON_RT = OuyaSDK.BUTTON_RT,
        BUTTON_L3 = OuyaSDK.BUTTON_L3,
        BUTTON_R3 = OuyaSDK.BUTTON_R3,
        BUTTON_SYSTEM = OuyaSDK.BUTTON_SYSTEM,
        BUTTON_START = OuyaSDK.BUTTON_START,
        BUTTON_SELECT = OuyaSDK.BUTTON_SELECT,
        BUTTON_ESCAPE = OuyaSDK.BUTTON_ESCAPE,
        AXIS_LSTICK_X = OuyaSDK.AXIS_LSTICK_X,
        AXIS_LSTICK_Y = OuyaSDK.AXIS_LSTICK_Y,
        AXIS_RSTICK_X = OuyaSDK.AXIS_RSTICK_X,
        AXIS_RSTICK_Y = OuyaSDK.AXIS_RSTICK_Y,
        BUTTON_DPAD_UP = OuyaSDK.BUTTON_DPAD_UP,
        BUTTON_DPAD_RIGHT = OuyaSDK.BUTTON_DPAD_RIGHT,
        BUTTON_DPAD_DOWN = OuyaSDK.BUTTON_DPAD_DOWN,
        BUTTON_DPAD_LEFT = OuyaSDK.BUTTON_DPAD_LEFT,
        BUTTON_DPAD_CENTER = OuyaSDK.BUTTON_DPAD_CENTER,

        BUTTON_BACK,

        HARMONIX_ROCK_BAND_GUITAR_GREEN,
        HARMONIX_ROCK_BAND_GUITAR_RED,
        HARMONIX_ROCK_BAND_GUITAR_YELLOW,
        HARMONIX_ROCK_BAND_GUITAR_BLUE,
        HARMONIX_ROCK_BAND_GUITAR_ORANGE,
        HARMONIX_ROCK_BAND_GUITAR_LOWER,
        HARMONIX_ROCK_BAND_GUITAR_WHAMMI,
        HARMONIX_ROCK_BAND_GUITAR_PICKUP,
        HARMONIX_ROCK_BAND_GUITAR_STRUM,

        HARMONIX_ROCK_BAND_DRUMKIT_GREEN,
        HARMONIX_ROCK_BAND_DRUMKIT_RED,
        HARMONIX_ROCK_BAND_DRUMKIT_YELLOW,
        HARMONIX_ROCK_BAND_DRUMKIT_BLUE,
        HARMONIX_ROCK_BAND_DRUMKIT_ORANGE,
        HARMONIX_ROCK_BAND_DRUMKIT_A,
        HARMONIX_ROCK_BAND_DRUMKIT_B,
        HARMONIX_ROCK_BAND_DRUMKIT_X,
        HARMONIX_ROCK_BAND_DRUMKIT_Y,

        HACK1 = 666,
#endif

        NumKeys
    }
}